# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harry/CS/Ophelia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harry/CS/Ophelia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harry/CS/Ophelia/CMakeFiles /home/harry/CS/Ophelia/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harry/CS/Ophelia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data

# Build rule for target.
data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data
.PHONY : data

# fast build rule for target.
data/fast:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/build
.PHONY : data/fast

#=============================================================================
# Target rules for targets named move

# Build rule for target.
move: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 move
.PHONY : move

# fast build rule for target.
move/fast:
	$(MAKE) -f CMakeFiles/move.dir/build.make CMakeFiles/move.dir/build
.PHONY : move/fast

#=============================================================================
# Target rules for targets named generator

# Build rule for target.
generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generator
.PHONY : generator

# fast build rule for target.
generator/fast:
	$(MAKE) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/build
.PHONY : generator/fast

#=============================================================================
# Target rules for targets named board

# Build rule for target.
board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board
.PHONY : board

# fast build rule for target.
board/fast:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/build
.PHONY : board/fast

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/board.dir/build.make CMakeFiles/board.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/data.o: src/data.cpp.o

.PHONY : src/data.o

# target to build an object file
src/data.cpp.o:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.cpp.o
.PHONY : src/data.cpp.o

src/data.i: src/data.cpp.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.cpp.i:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.cpp.i
.PHONY : src/data.cpp.i

src/data.s: src/data.cpp.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.cpp.s:
	$(MAKE) -f CMakeFiles/data.dir/build.make CMakeFiles/data.dir/src/data.cpp.s
.PHONY : src/data.cpp.s

src/generator.o: src/generator.cpp.o

.PHONY : src/generator.o

# target to build an object file
src/generator.cpp.o:
	$(MAKE) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/src/generator.cpp.o
.PHONY : src/generator.cpp.o

src/generator.i: src/generator.cpp.i

.PHONY : src/generator.i

# target to preprocess a source file
src/generator.cpp.i:
	$(MAKE) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/src/generator.cpp.i
.PHONY : src/generator.cpp.i

src/generator.s: src/generator.cpp.s

.PHONY : src/generator.s

# target to generate assembly for a file
src/generator.cpp.s:
	$(MAKE) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/src/generator.cpp.s
.PHONY : src/generator.cpp.s

src/move.o: src/move.cpp.o

.PHONY : src/move.o

# target to build an object file
src/move.cpp.o:
	$(MAKE) -f CMakeFiles/move.dir/build.make CMakeFiles/move.dir/src/move.cpp.o
.PHONY : src/move.cpp.o

src/move.i: src/move.cpp.i

.PHONY : src/move.i

# target to preprocess a source file
src/move.cpp.i:
	$(MAKE) -f CMakeFiles/move.dir/build.make CMakeFiles/move.dir/src/move.cpp.i
.PHONY : src/move.cpp.i

src/move.s: src/move.cpp.s

.PHONY : src/move.s

# target to generate assembly for a file
src/move.cpp.s:
	$(MAKE) -f CMakeFiles/move.dir/build.make CMakeFiles/move.dir/src/move.cpp.s
.PHONY : src/move.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... data"
	@echo "... move"
	@echo "... generator"
	@echo "... board"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/generator.o"
	@echo "... src/generator.i"
	@echo "... src/generator.s"
	@echo "... src/move.o"
	@echo "... src/move.i"
	@echo "... src/move.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

